services:
  nginx:
    container_name: hubii_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    # user: "nginx:nginx"
    ports:
      - 80:80
      - 443:443
    networks:
      - hubii_dev
    volumes:
      - ./nginx/config/certs:/etc/nginx/certs
      - ./nginx/config/conf.d:/etc/nginx/conf.d
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./home:/var/www/html
      # - ./logs/nginx:/var/log/nginx
    depends_on:
      - laravel_product
      - keycloak
  laravel_product:
    container_name: hubii_api_product
    build:
      context: ./apache
      dockerfile: Dockerfile
      args:
        WWWGROUP: ${WWWGROUP}
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8001:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: ${WWWUSER}
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}/api-product'
    volumes:
      - ./api-product:/var/www/html
    networks:
      - hubii_dev
    depends_on:
      - db

  # laravel_order:
  #   container_name: hubii_api_order
  #   build:
  #     context: ./api-order/vendor/laravel/sail/runtimes/8.2
  #     dockerfile: Dockerfile
  #     args:
  #       WWWGROUP: '${WWWGROUP}'
  #   image: sail-8.2/app
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
  #   ports:
  #     - '8002:80'
  #   environment:
  #     WWWUSER: '${WWWUSER}'
  #     LARAVEL_SAIL: 1
  #     XDEBUG_MODE: 'develop,debug,coverage'
  #     XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
  #     IGNITION_LOCAL_SITES_PATH: '${PWD}'
  #   volumes:
  #     - ./api-order:/var/www/html
  #   networks:
  #     - hubii_dev
  #   depends_on:
  #     - db
  # laravel_integration:
  #   container_name: hubii_api_orders
  #   build:
  #     context: ./api-order/vendor/laravel/sail/runtimes/8.2
  #     dockerfile: Dockerfile
  #     args:
  #       WWWGROUP: '${WWWGROUP}'
  #   image: sail-8.2/app
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
  #   ports:
  #     - '8003:80'
  #   environment:
  #     WWWUSER: '${WWWUSER}'
  #     LARAVEL_SAIL: 1
  #     XDEBUG_MODE: 'develop,debug,coverage'
  #     XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
  #     IGNITION_LOCAL_SITES_PATH: '${PWD}'
  #   volumes:
  #     - ./api-integration:/var/www/html
  #   networks:
  #     - hubii_dev
  #   depends_on:
  #     - db
  redis:
    container_name: hubii_redis
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - './redis/data:/data'
    networks:
      - hubii_dev
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: hubii_keycloak
    restart: unless-stopped
    volumes:
      - ./keycloak/data:/opt/keycloak/data/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE: MYSQL
      KEYCLOAK_DB_VENDOR: MYSQL
      KEYCLOAK_DB_ADDR: hubii_mysql # MySQL server address
      KEYCLOAK_DB_PORT: 3306 # MySQL server port
      KEYCLOAK_DB_DATABASE: hubii_test # MySQL database name
      KEYCLOAK_DB_USER: hubii # MySQL database user
      KEYCLOAK_DB_PASSWORD: hubii # MySQL database password
      KEYCLOAK_FRONTEND_URL: https://hubii.keycloak.local/auth
      KEYCLOAK_PROXY_ADDRESS_FORWARDING: true 
    command: [ "start-dev", '--hostname-strict=false']
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - hubii_dev
  db:
    container_name: hubii_mysql
    image: mysql:8.0.35
    restart: unless-stopped
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hubii_test
      MYSQL_USER: hubii
      MYSQL_PASSWORD: hubii
    ports:
      - "3308:3306"
    networks:
      - hubii_dev
networks:
  hubii_dev:
    driver: bridge
